"""Generate frontend/data/teams-meta.json from CFBD team metadata (EPIC-044 Story 44.9).

The Ticker board/predictions/bracket merge per-team display data (abbreviation,
mascot, brand colors) onto the API rankings by Team.name. CFBD's /teams/fbs
'school' matches our Team.name 1:1, so we key the file by Team.name and pull
abbreviation / mascot / color / alternateColor straight from CFBD.

Re-run after roster/season updates:
    set -a && source .env && set +a
    arch -x86_64 /usr/local/bin/python3.11 utilities/gen_team_meta.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.integrations.cfbd_client import CFBDClient
from src.models.database import SessionLocal
from src.models.models import Team

OUT = os.path.join("frontend", "data", "teams-meta.json")
FBS_CONFS = ("P5", "P4", "G5")


def main() -> None:
    cfbd = CFBDClient()
    data = cfbd.get_teams(2025) or cfbd.get_teams(2024) or []
    by_school = {t.get("school"): t for t in data}

    db = SessionLocal()
    fbs = [t for t in db.query(Team).all() if getattr(t, "conference", None) in FBS_CONFS]

    meta = {
        "_note": "Generated by utilities/gen_team_meta.py from CFBD /teams/fbs. "
        "Keyed by Team.name. Re-run to refresh; do not hand-edit.",
    }
    missing_color = []
    for t in sorted(fbs, key=lambda x: x.name):
        cf = by_school.get(t.name)
        if not cf:
            continue
        entry = {}
        if cf.get("abbreviation"):
            entry["abbr"] = cf["abbreviation"]
        if cf.get("mascot"):
            entry["mascot"] = cf["mascot"]
        if cf.get("color"):
            entry["primary"] = cf["color"]
        secondary = cf.get("alternateColor") or cf.get("alt_color")
        if secondary:
            entry["secondary"] = secondary
        if not entry.get("primary"):
            missing_color.append(t.name)
        meta[t.name] = entry

    with open(OUT, "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")

    print(f"wrote {OUT}: {len(meta) - 1} teams; {len(missing_color)} without a primary color")
    if missing_color:
        print("no color:", missing_color)


if __name__ == "__main__":
    main()
